# by default, the Ghost image will use SQLite (and thus requires no separate database container)
# we have used MySQL here merely for demonstration purposes (especially environment-variable-based configuration)

version: '3.1'

services:

  ghost:
    image: ghost
    restart: always
    volumes:
      - content:/var/lib/ghost/content
    environment:
      url: https://ghost.halfassedmarketing.com

  ghost_backup:
    build: ./ghostbackup
    volumes:
      - content:/content
    secrets:
      - gcloud_auth.json

  nginx:
    image: nginx
    restart: always
    ports: 
      - "80:80"
      - "443:443"
    volumes:
      - certs:/etc/nginx/certs
      - webroot:/usr/share/nginx/html

  certbot:
    image: certbot/certbot
    volumes:
      - certs:/etc/letsencrypt/live/ghost.halfassedmarketing.com/
      - webroot:/webroot

volumes:
    content:
    certs:
    webroot:

secrets:
  gcloud_auth.json:
    file: ./secrets/gcloud_auth.json
