version: '3.1'

services:

  ghost:
    image: ghost
    restart: always
    volumes:
      - content:/var/lib/ghost/content
    ports:
      - "2368:2368"
    environment:
      url: https://${HTTPS_DOMAIN}
      mail__transport: "SMTP"
      mail__options__host: "mail"
      mail__options__port: "587"
      mail__options__auth__user: "${MAIL_USER}@${HTTPS_DOMAIN}"
      mail__options__auth__pass: "${MAIL_PASS}"
      
  mail:
    image: catatnight/postfix
    restart: always
    volumes: 
      - certs:/etc/posftix/certs
    ports:
      - "587:587"
    environment:
      maildomain: ${HTTPS_DOMAIN}
      smtp_user: ${MAIL_USER}@${HTTPS_DOMAIN}:${MAIL_PASS}

  ghost_backup:
    build: ./ghostbackup
    volumes:
      - content:/content
    secrets:
      - gcloud_auth.json

  nginx:
    image: nginx
    restart: always
    ports: 
      - "80:80"
      - "443:443"
    volumes:
      - certs:/etc/letsencrypt
      - webroot:/usr/share/nginx/html
      - nginxconf:/etc/nginx/conf.d/

  certbot:
    image: certbot/certbot
    volumes:
      - certs:/etc/letsencrypt/
      - webroot:/webroot
      
volumes:
  content:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: $PWD/environment/content
  certs:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: $PWD/environment/certs
  webroot:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: $PWD/environment/webroot
  nginxconf:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: $PWD/environment/nginxconf

secrets:
  gcloud_auth.json:
    file: ./secrets/gcloud_auth.json
