# by default, the Ghost image will use SQLite (and thus requires no separate database container)
# we have used MySQL here merely for demonstration purposes (especially environment-variable-based configuration)

version: '3.1'

services:

  ghost:
    image: ghost
    restart: always
    volumes:
      - ./environment/content:/var/lib/ghost/content
    environment:
      url: https://writer.halfassedmarketing.com

  ghost_backup:
    build: ./ghostbackup
    volumes:
      - ./environment/content:/content
    secrets:
      - gcloud_auth.json

  nginx:
    image: nginx
    restart: always
    ports: 
      - "80:80"
      - "443:443"
    volumes:
      - ./environment/certs:/etc/letsencrypt
      - ./environment/webroot:/usr/share/nginx/html
      - ./environment/nginxconf:/etc/nginx/conf.d/

  certbot:
    image: certbot/certbot
    volumes:
      - ./environment/certs:/etc/letsencrypt/
      - ./environment/webroot:/webroot
      
volumes:
  content:
  certs:
  webroot:
  nginxconf:

secrets:
  gcloud_auth.json:
    file: ./secrets/gcloud_auth.json