# by default, the Ghost image will use SQLite (and thus requires no separate database container)
# we have used MySQL here merely for demonstration purposes (especially environment-variable-based configuration)

version: '3.1'

services:

  ghost:
    image: ghost
    restart: always
    ports:
      - "678:2368"
    volumes:
      - content:/var/lib/ghost/content
    environment:
      url: http://ghost:678

  nginx:
    image: nginx

volumes:
    content:
